name: artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.1
      - name: Upload the artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ${{ env.ARTIFACT_NAME}}
          path: .
